# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3E69K0KuQKkU10jCC3_kGjaF9zb5-zP
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SnowVolt Dashboard", layout="wide")

st.title("❄️ SnowVolt: TENG-Based Renewable Energy Monitoring")
st.markdown("Monitor battery levels, snow depth, temperature and energy from simulated snow-based sensors.")

# Load data
df = pd.read_csv("/content/snowvolt_data_for_powerbi.csv")
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

# KPIs
latest = df.iloc[-1]
col1, col2, col3, col4 = st.columns(4)
col1.metric("🔋 Battery (%)", f"{latest['Battery (%)']:.1f}%")
col2.metric("❄️ Max Snow Depth", f"{df['Snow Depth (cm)'].max()} cm")
col3.metric("⚡ Total Energy", f"{df['Energy (mW)'].sum():.1f} mW")
col4.metric("🌡️ Avg Temperature", f"{df['Temperature (°C)'].mean():.1f}°C")

# Filters
with st.sidebar:
    st.header("🔍 Filters")
    snow_filter = st.slider("Snow Depth (cm)", int(df["Snow Depth (cm)"].min()), int(df["Snow Depth (cm)"].max()), (5, 25))
    temp_filter = st.slider("Temperature (°C)", int(df["Temperature (°C)"].min()), int(df["Temperature (°C)"].max()), (0, 25))

df_filtered = df[(df["Snow Depth (cm)"].between(*snow_filter)) & (df["Temperature (°C)"].between(*temp_filter))]

# Charts
st.subheader("📈 Battery Over Time")
fig1 = px.line(df_filtered, x="Timestamp", y="Battery (%)", markers=True)
st.plotly_chart(fig1, use_container_width=True)

st.subheader("❄️ Snow Depth vs Energy")
fig2 = px.scatter(df_filtered, x="Snow Depth (cm)", y="Energy (mW)", color="Temperature (°C)", size="Humidity (%)", hover_data=["Battery (%)", "Timestamp"])
st.plotly_chart(fig2, use_container_width=True)

# Data and Download
st.subheader("📄 View or Download Data")
st.dataframe(df_filtered)
st.download_button("📥 Download CSV", df_filtered.to_csv(index=False), file_name="filtered_snowvolt_data.csv")