# -*- coding: utf-8 -*-
"""snowvolt_dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMjZ2wNvkP-OHVaJOWLsNksT52ptT29-
"""

!pip install streamlit

import streamlit as st
import random
import pandas as pd
import os

st.set_page_config(page_title="SnowVolt Dashboard", layout="wide")
st.title("❄️ SnowVolt Dashboard - TENG Snow Energy Monitor")

# CSV Logging Function
def log_to_csv(data, filename="snowvolt_log.csv"):
    df = pd.DataFrame([data], columns=["Snow Depth (cm)", "Temperature (°C)", "Humidity (%)", "Energy (mW)", "Battery (%)"])
    if os.path.exists(filename):
        df.to_csv(filename, mode='a', header=False, index=False)
    else:
        df.to_csv(filename, index=False)

# Simulated Sensor Data Generator
def get_sensor_data():
    snow_depth = round(random.uniform(0, 50), 2)
    temperature = round(random.uniform(-20, 5), 1)
    humidity = round(random.uniform(30, 90), 1)
    energy_generated = round(snow_depth * random.uniform(0.01, 0.05), 2)
    battery_storage = min(100, round(energy_generated * random.uniform(1, 3), 1))
    return snow_depth, temperature, humidity, energy_generated, battery_storage

# Sidebar Project Info
st.sidebar.title("📌 Project Info")
st.sidebar.markdown("""
**Project:** SnowVolt
**Concept:** Snow-based renewable energy
**Technology:** Triboelectric Nanogenerator (TENG)
**User:** Researchers, Smart Cities, Military Zones
""")

# Simulate and Log Data
snow_depth, temperature, humidity, energy, battery = get_sensor_data()
log_to_csv([snow_depth, temperature, humidity, energy, battery])

# Display Metrics
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("🌨️ Snow Depth", f"{snow_depth} cm")
    st.metric("💧 Humidity", f"{humidity}%")
with col2:
    st.metric("🌡️ Temperature", f"{temperature}°C")
    st.metric("⚡ Energy", f"{energy} mW")
with col3:
    st.metric("🔋 Battery", f"{battery}%")
    if battery < 30:
        st.error("🔻 Battery Low")
    elif battery > 80:
        st.success("🔋 Battery Healthy")
    else:
        st.warning("🟡 Battery Moderate")

st.divider()

# Load or Create CSV File
if os.path.exists("snowvolt_log.csv"):
    df = pd.read_csv("snowvolt_log.csv")
    st.subheader("📈 Recent Sensor Data Logs")
    st.dataframe(df.tail(10))

    st.subheader("📊 Battery Trend")
    st.line_chart(df["Battery (%)"].tail(10))

    st.download_button(
        label="📥 Download Sensor Log (CSV)",
        data=df.to_csv(index=False),
        file_name="snowvolt_log.csv",
        mime="text/csv"
    )
else:
    st.warning("No data logged yet. Refresh the app to begin collecting sensor data.")

st.caption("Simulated dashboard. Data is generated via Python logic for SnowVolt prototyping.")

from google.colab import files
files.download('snowvolt_log.csv')

import pandas as pd
df = pd.read_csv('snowvolt_log.csv')
df.tail(10)